# Branch Protection Rules Configuration
# This file documents the recommended branch protection settings
# Apply these settings in GitHub repository settings

main:
  # Require pull request reviews before merging
  required_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_approving_review_count: 2
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: true # Require branches to be up to date before merging
    contexts:
      - "Security Scan"
      - "Lint & Type Check"
      - "Unit & Integration Tests"
      - "E2E Tests (chromium)"
      - "E2E Tests (firefox)"
      - "E2E Tests (webkit)"
      - "Build Check"
      - "All Tests Passed"
      
  # Enforce restrictions
  restrictions:
    users: []
    teams: ["engineering-leads"]
    apps: ["renovate[bot]", "dependabot[bot]"]
    
  # Additional settings
  enforce_admins: true
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  lock_branch: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  
  # Require conversation resolution before merging
  required_conversation_resolution: true
  
  # Require signed commits
  required_signatures: true

staging:
  # Require pull request reviews before merging
  required_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_approving_review_count: 1
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - "Security Scan"
      - "Lint & Type Check"
      - "Unit & Integration Tests"
      - "Build Check"
      
  # Enforce restrictions
  restrictions:
    users: []
    teams: ["engineering"]
    apps: ["renovate[bot]", "dependabot[bot]"]
    
  # Additional settings
  enforce_admins: false
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  lock_branch: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  
  # Require conversation resolution before merging
  required_conversation_resolution: true

develop:
  # Require pull request reviews before merging
  required_reviews:
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    required_approving_review_count: 1
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: false
    contexts:
      - "Lint & Type Check"
      - "Unit & Integration Tests"
      
  # No restrictions on develop branch
  restrictions: null
    
  # Additional settings
  enforce_admins: false
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false
  lock_branch: false
  allow_auto_merge: true
  delete_branch_on_merge: true